Use GH_TOKEN for PR label

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -142,6 +142,7 @@ jobs:
     needs: combine
     permissions:
       id-token: write
+      pull-requests: write
 
     steps:
       - name: Log in to Azure
@@ -170,7 +171,6 @@ jobs:
           owner: bitwarden
           repositories: android
           permission-actions: write
-          permission-pull-requests: write
 
       - name: Trigger SDK Update in Android repo
         if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.update-android-repo
@@ -183,14 +183,13 @@ jobs:
           gh workflow run sdlc-sdk-update.yml --repo bitwarden/android --ref main -f run-mode=Update -f sdk-package=$_SDK_PACKAGE -f sdk-version=$_SDK_VERSION
 
       - name: Trigger SDK Test in Android repo and wait for completion
+        id: test-android
         if: github.event_name == 'pull_request' || inputs.test-android-repo
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           _SDK_PACKAGE: "com.bitwarden:sdk-android" #${{ needs.combine.outputs.sdk-package-id
           _SDK_VERSION: "1.0.0-2493-bceb681a" #${{ needs.combine.outputs.sdk-version
-          _PR_NUMBER: ${{ github.event.pull_request.number }}
           _MAX_RUN_LIST_RETRIES: 5
-          _BREAKING_CHANGE_LABEL: "breaking-change-android"
         run: |
           echo "🚀 Triggering sdlc-sdk-update.yml workflow in bitwarden/android repo..."
           json_params='{"run-mode": "Test", "sdk-package": "'"$_SDK_PACKAGE"'", "sdk-version": "'"$_SDK_VERSION"'", "pr-id": "'"$_PR_NUMBER"'"}'
@@ -231,8 +230,19 @@ jobs:
             LABEL_ACTION="--remove-label"
           fi
 
-          if [ -n "$_PR_NUMBER" ]; then
-            gh pr edit --repo bitwarden/sdk-internal $_PR_NUMBER $LABEL_ACTION $_BREAKING_CHANGE_LABEL
-          fi
+          echo "label-action=$LABEL_ACTION" >> $GITHUB_OUTPUT
+          echo "error-code=$ERROR_CODE" >> $GITHUB_OUTPUT
 
-          exit $ERROR_CODE
+      - name: Label PR and exit
+        if: github.event_name == 'pull_request' || inputs.test-android-repo
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          _LABEL_ACTION: ${{ steps.test-android.outputs.label-action }}
+          _ERROR_CODE: ${{ steps.test-android.outputs.error-code }}
+          _PR_NUMBER: ${{ github.event.pull_request.number }}
+          _BREAKING_CHANGE_LABEL: "breaking-change-android"
+        run: |
+          if [ -n "$_PR_NUMBER" ]; then
+            gh pr edit --repo bitwarden/sdk-internal $_PR_NUMBER $_LABEL_ACTION $_BREAKING_CHANGE_LABEL
+          fi
+          exit $_ERROR_CODE
