Switch branch

diff --git a/.github/workflows/download-server-artifact.yml b/.github/workflows/download-server-artifact.yml
--- a/.github/workflows/download-server-artifact.yml
+++ b/.github/workflows/download-server-artifact.yml
@@ -51,6 +51,50 @@ jobs:
           token: ${{ steps.app-token.outputs.token }}
           fetch-depth: 0
 
+      - name: Switch to branch
+        id: switch-branch
+        run: |
+          BRANCH_NAME="sdlc/api-update"
+          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
+
+          if git switch $BRANCH_NAME; then
+            echo "✅ Switched to existing branch: $BRANCH_NAME"
+            echo "updating_existing_branch=true" >> $GITHUB_OUTPUT
+          else
+            echo "📝 Creating new branch: $BRANCH_NAME"
+            git switch -c $BRANCH_NAME
+            echo "updating_existing_branch=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Prevent updating the branch when the last committer isn't the bot
+        if: ${{ steps.switch-branch.outputs.updating_existing_branch == 'true' }}
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+          _BRANCH_NAME: ${{ steps.switch-branch.outputs.branch_name }}
+        run: |
+          LATEST_COMMIT_AUTHOR=$(git log -1 --format='%ae' $_BRANCH_NAME)
+
+          echo "Latest commit author in branch ($_BRANCH_NAME): $LATEST_COMMIT_AUTHOR"
+          echo "Expected bot email: $_BOT_EMAIL"
+
+          if [ "$LATEST_COMMIT_AUTHOR" != "$_BOT_EMAIL" ]; then
+            echo "::error::Branch $_BRANCH_NAME has a commit not made by the bot." \
+              "This indicates manual changes have been made to the branch," \
+              "PR has to be merged or closed before running this workflow again."
+            echo "👀 Fetching existing PR..."
+            gh pr list --head $_BRANCH_NAME --base main --state open --json number --jq '.[0].number // empty'
+            EXISTING_PR=$(gh pr list --head $_BRANCH_NAME --base main --state open --json number --jq '.[0].number // empty')
+            if [ -z "$EXISTING_PR" ]; then
+              echo "::error::Couldn't find an existing PR for branch $_BRANCH_NAME."
+              exit 1
+            fi
+            PR_URL="https://github.com/${{ github.repository }}/pull/$EXISTING_PR"
+            echo "## ❌ Merge or close: $PR_URL" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+
+          echo "✅ Branch tip commit was made by the bot. Safe to proceed."
+
       - name: Download json artifacts
         uses: bitwarden/gh-actions/download-artifacts@main
         with:
@@ -114,15 +158,12 @@ jobs:
         id: commit-info
         run: |
           HASH=$(cat ./artifacts/identity.json | jq -r '.["x-git-commit"]')
-          BRANCH_NAME=api/$HASH
-
           echo "HASH=$HASH" >> $GITHUB_OUTPUT
-          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
 
       - name: Create branch and commit
         env:
           _HASH: ${{ steps.commit-info.outputs.HASH }}
-          _BRANCH_NAME: ${{ steps.commit-info.outputs.BRANCH_NAME }}
+          _BRANCH_NAME: ${{ steps.switch-branch.outputs.BRANCH_NAME }}
         run: |
           echo "👀 Committing SDK version update..."
 
@@ -137,7 +178,7 @@ jobs:
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           _HASH: ${{ steps.commit-info.outputs.HASH }}
-          _BRANCH_NAME: ${{ steps.commit-info.outputs.BRANCH_NAME }}
+          _BRANCH_NAME: ${{ steps.switch-branch.outputs.BRANCH_NAME }}
         run: |
           PR_BODY="Updates the API bindings to \`$_HASH\`
 
